//! Shannon entropy calculator for heuristic analysis.
//!
//! Computes byte-level Shannon entropy for entire files and per-section regions.
//! High entropy indicates packed, encrypted, or compressed content — a common
//! characteristic of malware that tries to evade signature-based detection.

use guardian_common::config::HeuristicConfig;

/// Entropy analysis results for a file or region.
#[derive(Debug, Clone)]
pub struct EntropyResult {
    /// Overall Shannon entropy (0.0 - 8.0).
    pub overall: f64,
    /// Per-section entropies (offset, length, entropy).
    pub sections: Vec<SectionEntropy>,
    /// Risk score contribution (0 - 10).
    pub score: u32,
    /// Human-readable classification.
    pub classification: EntropyClassification,
}

/// Entropy for a named or offset-identified section.
#[derive(Debug, Clone)]
pub struct SectionEntropy {
    /// Section name (if available) or hex offset label.
    pub name: String,
    /// Byte offset in the file.
    pub offset: usize,
    /// Length of the section.
    pub length: usize,
    /// Shannon entropy value (0.0 - 8.0).
    pub entropy: f64,
}

/// Classification based on entropy value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntropyClassification {
    /// Entropy < 6.0 — normal uncompressed data.
    Normal,
    /// Entropy 6.0..7.0 — normal compressed data (ZIP, images, etc.).
    Compressed,
    /// Entropy 7.0..7.5 — suspicious, may be obfuscated.
    Suspicious,
    /// Entropy >= 7.5 — likely packed or encrypted.
    PackedOrEncrypted,
}

/// Compute byte-level Shannon entropy for a data slice.
///
/// Returns a value between 0.0 (completely uniform) and 8.0 (maximum entropy
/// for byte-level analysis, i.e. perfectly random bytes).
pub fn shannon_entropy(data: &[u8]) -> f64 {
    if data.is_empty() {
        return 0.0;
    }

    let mut frequency = [0u64; 256];
    for &byte in data {
        frequency[byte as usize] += 1;
    }

    let len = data.len() as f64;
    let mut entropy = 0.0f64;

    for &count in &frequency {
        if count == 0 {
            continue;
        }
        let p = count as f64 / len;
        entropy -= p * p.log2();
    }

    entropy
}

/// Classify an entropy value into a human-readable category.
pub fn classify_entropy(entropy: f64, config: &HeuristicConfig) -> EntropyClassification {
    if entropy >= config.entropy_packed {
        EntropyClassification::PackedOrEncrypted
    } else if entropy >= config.entropy_suspicious {
        EntropyClassification::Suspicious
    } else if entropy >= 6.0 {
        EntropyClassification::Compressed
    } else {
        EntropyClassification::Normal
    }
}

/// Map an entropy classification to a risk score contribution (0-10).
fn classification_to_score(class: EntropyClassification) -> u32 {
    match class {
        EntropyClassification::Normal => 0,
        EntropyClassification::Compressed => 1,
        EntropyClassification::Suspicious => 4,
        EntropyClassification::PackedOrEncrypted => 8,
    }
}

/// Analyze a file's entropy, both overall and per-section.
///
/// Sections are generated by splitting the file into fixed-size chunks (default
/// 4096 bytes) to detect regions with anomalous entropy, such as encrypted
/// payloads embedded in an otherwise normal binary.
pub fn analyze_entropy(data: &[u8], config: &HeuristicConfig) -> EntropyResult {
    let overall = shannon_entropy(data);
    let classification = classify_entropy(overall, config);

    let section_size = 4096;
    let mut sections = Vec::new();

    if data.len() > section_size {
        for (i, chunk) in data.chunks(section_size).enumerate() {
            let offset = i * section_size;
            let ent = shannon_entropy(chunk);
            sections.push(SectionEntropy {
                name: format!("chunk_0x{:06x}", offset),
                offset,
                length: chunk.len(),
                entropy: ent,
            });
        }
    }

    // Base score from overall classification.
    let mut score = classification_to_score(classification);

    // Bonus: if there are high-entropy sections embedded in an otherwise
    // normal-entropy file, it is suspicious (possible encrypted payload).
    if classification == EntropyClassification::Normal
        || classification == EntropyClassification::Compressed
    {
        let high_entropy_sections = sections
            .iter()
            .filter(|s| s.entropy >= config.entropy_packed)
            .count();
        if high_entropy_sections > 0 {
            // At least one packed section in a normal file — bump the score.
            score = score.saturating_add(
                (high_entropy_sections as u32).min(5),
            );
        }
    }

    // Cap at 10.
    score = score.min(10);

    EntropyResult {
        overall,
        sections,
        score,
        classification,
    }
}

/// Analyze entropy for explicitly named sections (e.g., PE sections parsed
/// externally). Each entry is `(name, offset, data_slice)`.
pub fn analyze_named_sections(
    sections: &[(&str, usize, &[u8])],
    _config: &HeuristicConfig,
) -> Vec<SectionEntropy> {
    sections
        .iter()
        .map(|(name, offset, data)| {
            let entropy = shannon_entropy(data);
            SectionEntropy {
                name: name.to_string(),
                offset: *offset,
                length: data.len(),
                entropy,
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn default_config() -> HeuristicConfig {
        HeuristicConfig::default()
    }

    #[test]
    fn test_entropy_empty() {
        assert_eq!(shannon_entropy(b""), 0.0);
    }

    #[test]
    fn test_entropy_uniform_single_byte() {
        // All identical bytes → entropy = 0.
        let data = vec![0xAA; 1024];
        let e = shannon_entropy(&data);
        assert!(e.abs() < 0.001, "Expected ~0, got {}", e);
    }

    #[test]
    fn test_entropy_two_equal_bytes() {
        // Exactly two byte values, equally distributed → entropy = 1.0.
        let mut data = vec![0u8; 1024];
        for i in 0..512 {
            data[i] = 0;
        }
        for i in 512..1024 {
            data[i] = 1;
        }
        let e = shannon_entropy(&data);
        assert!(
            (e - 1.0).abs() < 0.01,
            "Expected ~1.0, got {}",
            e
        );
    }

    #[test]
    fn test_entropy_random_high() {
        // Pseudo-random data should have high entropy (close to 8.0).
        let data: Vec<u8> = (0..=255).cycle().take(256 * 100).collect();
        let e = shannon_entropy(&data);
        assert!(
            e > 7.9,
            "Expected near 8.0 for uniformly distributed bytes, got {}",
            e
        );
    }

    #[test]
    fn test_entropy_ascii_text() {
        // English text typically has entropy around 4.0-5.0.
        let text = b"The quick brown fox jumps over the lazy dog. \
                     This is a reasonably long sentence with various letters \
                     and common English words that should produce moderate entropy.";
        let e = shannon_entropy(text);
        assert!(e > 3.5 && e < 5.5, "Expected 3.5-5.5, got {}", e);
    }

    #[test]
    fn test_classify_normal() {
        let cfg = default_config();
        assert_eq!(
            classify_entropy(4.5, &cfg),
            EntropyClassification::Normal
        );
    }

    #[test]
    fn test_classify_compressed() {
        let cfg = default_config();
        assert_eq!(
            classify_entropy(6.5, &cfg),
            EntropyClassification::Compressed
        );
    }

    #[test]
    fn test_classify_suspicious() {
        let cfg = default_config();
        assert_eq!(
            classify_entropy(7.2, &cfg),
            EntropyClassification::Suspicious
        );
    }

    #[test]
    fn test_classify_packed() {
        let cfg = default_config();
        assert_eq!(
            classify_entropy(7.8, &cfg),
            EntropyClassification::PackedOrEncrypted
        );
    }

    #[test]
    fn test_analyze_entropy_small_file() {
        let cfg = default_config();
        let data = vec![0x42; 100]; // small, uniform → no sections
        let result = analyze_entropy(&data, &cfg);
        assert_eq!(result.overall, 0.0);
        assert!(result.sections.is_empty());
        assert_eq!(result.score, 0);
        assert_eq!(result.classification, EntropyClassification::Normal);
    }

    #[test]
    fn test_analyze_entropy_large_uniform() {
        let cfg = default_config();
        let data = vec![0x00; 16384];
        let result = analyze_entropy(&data, &cfg);
        assert_eq!(result.overall, 0.0);
        assert_eq!(result.sections.len(), 4); // 16384 / 4096
        assert_eq!(result.score, 0);
    }

    #[test]
    fn test_analyze_entropy_mixed_content() {
        let cfg = default_config();
        // 4096 bytes of zeros + 4096 bytes of pseudo-random
        let mut data = vec![0x00u8; 4096];
        let random_section: Vec<u8> = (0..=255).cycle().take(4096).collect();
        data.extend_from_slice(&random_section);

        let result = analyze_entropy(&data, &cfg);
        assert_eq!(result.sections.len(), 2);

        // First section should be zero entropy.
        assert!(
            result.sections[0].entropy < 0.01,
            "First section should be ~0, got {}",
            result.sections[0].entropy
        );

        // Second section should have high entropy.
        assert!(
            result.sections[1].entropy > 7.5,
            "Second section should be >7.5, got {}",
            result.sections[1].entropy
        );

        // Score should be boosted because of the high-entropy section.
        assert!(result.score > 0, "Score should be > 0 due to high-entropy section");
    }

    #[test]
    fn test_analyze_named_sections() {
        let cfg = default_config();
        let text_data = b"Hello world, this is normal text data.";
        let random_data: Vec<u8> = (0..=255).cycle().take(1024).collect();

        let sections = vec![
            (".text", 0, text_data.as_slice()),
            (".packed", 1000, random_data.as_slice()),
        ];

        let results = analyze_named_sections(&sections, &cfg);
        assert_eq!(results.len(), 2);
        assert_eq!(results[0].name, ".text");
        assert_eq!(results[1].name, ".packed");
        assert!(results[1].entropy > results[0].entropy);
    }

    #[test]
    fn test_score_capped_at_10() {
        let cfg = default_config();
        // All high-entropy data → score should not exceed 10.
        let data: Vec<u8> = (0..=255).cycle().take(256 * 200).collect();
        let result = analyze_entropy(&data, &cfg);
        assert!(result.score <= 10, "Score must be <= 10, got {}", result.score);
    }
}
