"""AI Risk Manager — monitors all agents and enforces risk limits.

The Risk Manager acts as a safety net across the entire simulation:
1. Monitors individual agent drawdowns and disables dangerous agents
2. Tracks group-level exposure and correlation
3. Enforces position limits and leverage caps
4. Detects anomalous behavior (flash crash, stuck strategies, etc.)
5. Generates risk alerts for the AI Teacher to act on

Risk Rules (Binance Futures style):
- Max drawdown per agent: 30% (warning at 20%)
- Max leverage: 125x BTC, 100x ETH, 75x others
- Max portfolio exposure: 50% of total capital in one direction
- Liquidation buffer: Alert when within 5% of liquidation
- Correlation alert: When >80% of agents agree on direction
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import numpy as np

from src.agents.base_agent import AgentGroup, TradingAgent
from src.core.models import Candle, Side

logger = logging.getLogger(__name__)


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class RiskAlert:
    """A risk alert generated by the Risk Manager."""
    level: RiskLevel
    agent_id: Optional[str]
    group_name: Optional[str]
    category: str  # "drawdown", "leverage", "exposure", "correlation", "liquidation"
    message: str
    metric_value: float = 0.0
    threshold: float = 0.0
    action_taken: str = ""  # What the risk manager did about it


@dataclass
class RiskConfig:
    # Agent-level limits
    max_drawdown_warning: float = 0.20  # 20% drawdown → warning
    max_drawdown_critical: float = 0.30  # 30% drawdown → disable agent
    max_daily_trades: int = 50
    max_leverage: int = 125

    # Group-level limits
    max_group_exposure_pct: float = 0.50  # 50% of total capital
    correlation_alert_threshold: float = 0.80  # 80% agents in same direction

    # Liquidation proximity
    liquidation_proximity_warning: float = 0.10  # Warn at 10% from liquidation
    liquidation_proximity_critical: float = 0.05  # Critical at 5%

    # Performance thresholds for teacher feedback
    excellent_pnl_pct: float = 10.0
    good_pnl_pct: float = 3.0
    poor_pnl_pct: float = -5.0
    terrible_pnl_pct: float = -15.0

    excellent_win_rate: float = 0.60
    good_win_rate: float = 0.50
    poor_win_rate: float = 0.40


class RiskManager:
    """Monitors risk across all agents and groups.

    Runs every candle (or periodically) and generates risk alerts.
    The AI Teacher uses these alerts to provide feedback and guidance.

    Includes turbulence index (Yang et al., 2020) — Mahalanobis distance
    of multi-asset returns to detect abnormal market conditions.
    """

    def __init__(self, config: Optional[RiskConfig] = None):
        self.config = config or RiskConfig()
        self.alerts: list[RiskAlert] = []
        self.alerts_history: list[RiskAlert] = []
        self.disabled_agents: set[str] = set()
        self.check_count = 0

        # Turbulence index tracking (Yang et al., 2020)
        self.turbulence_index: float = 0.0
        self.turbulence_history: list[float] = []
        self._returns_history: list[dict[str, float]] = []  # [{symbol: return}, ...]

        # Per-symbol crowding tracker
        self.symbol_crowding: dict[str, dict[str, int]] = {}  # {symbol: {LONG: n, SHORT: n}}

    def check_all(self, groups: list[AgentGroup]) -> list[RiskAlert]:
        """Run all risk checks and enforce critical actions. Returns new alerts.

        Two-phase approach (command-query separation):
        1. _check_* methods only generate alerts (pure queries)
        2. _enforce_alerts() applies side effects (disable agents, etc.)
        """
        self.check_count += 1
        new_alerts = []

        for group in groups:
            new_alerts.extend(self._check_group(group))
            for agent in group.agents:
                new_alerts.extend(self._check_agent(agent, group.name))

        # Portfolio-wide checks
        new_alerts.extend(self._check_correlation(groups))

        # Enforce actions from critical alerts
        self._enforce_alerts(new_alerts, groups)

        self.alerts = new_alerts
        self.alerts_history.extend(new_alerts)
        return new_alerts

    def _enforce_alerts(
        self, alerts: list[RiskAlert], groups: list[AgentGroup]
    ) -> None:
        """Apply side effects from risk alerts (separate from checking)."""
        for alert in alerts:
            if alert.action_taken != "AGENT_DISABLED":
                continue
            if not alert.agent_id:
                continue
            for group in groups:
                for agent in group.agents:
                    if agent.id == alert.agent_id and agent.active:
                        agent.active = False
                        self.disabled_agents.add(agent.id)
                        logger.warning(f"Risk enforcement: disabled {agent.config.name}")

    def _check_agent(self, agent: TradingAgent, group_name: str) -> list[RiskAlert]:
        """Check individual agent risk metrics."""
        alerts = []
        account = agent.account
        if not account or not agent.active:
            return alerts

        # 1. Drawdown check (generate alert only; enforcement is in _enforce_alerts)
        if account.max_drawdown >= self.config.max_drawdown_critical:
            alerts.append(RiskAlert(
                level=RiskLevel.CRITICAL,
                agent_id=agent.id,
                group_name=group_name,
                category="drawdown",
                message=(
                    f"Agent {agent.config.name} DISABLED: "
                    f"drawdown {account.max_drawdown:.1%} exceeds "
                    f"{self.config.max_drawdown_critical:.0%} limit"
                ),
                metric_value=account.max_drawdown,
                threshold=self.config.max_drawdown_critical,
                action_taken="AGENT_DISABLED",
            ))
        elif account.max_drawdown >= self.config.max_drawdown_warning:
            alerts.append(RiskAlert(
                level=RiskLevel.HIGH,
                agent_id=agent.id,
                group_name=group_name,
                category="drawdown",
                message=(
                    f"Agent {agent.config.name}: high drawdown "
                    f"{account.max_drawdown:.1%} (limit: {self.config.max_drawdown_critical:.0%})"
                ),
                metric_value=account.max_drawdown,
                threshold=self.config.max_drawdown_warning,
            ))

        # 2. Liquidation proximity check
        for pos_id, position in account.positions.items():
            current_price = agent.exchange.current_prices.get(position.symbol, 0)
            if current_price <= 0 or position.liquidation_price <= 0:
                continue

            if position.side == Side.LONG:
                distance = (current_price - position.liquidation_price) / current_price
            else:
                distance = (position.liquidation_price - current_price) / current_price

            if distance < self.config.liquidation_proximity_critical:
                alerts.append(RiskAlert(
                    level=RiskLevel.CRITICAL,
                    agent_id=agent.id,
                    group_name=group_name,
                    category="liquidation",
                    message=(
                        f"Agent {agent.config.name}: {position.symbol} "
                        f"NEAR LIQUIDATION ({distance:.1%} away)"
                    ),
                    metric_value=distance,
                    threshold=self.config.liquidation_proximity_critical,
                ))
            elif distance < self.config.liquidation_proximity_warning:
                alerts.append(RiskAlert(
                    level=RiskLevel.HIGH,
                    agent_id=agent.id,
                    group_name=group_name,
                    category="liquidation",
                    message=(
                        f"Agent {agent.config.name}: {position.symbol} "
                        f"approaching liquidation ({distance:.1%} away)"
                    ),
                    metric_value=distance,
                    threshold=self.config.liquidation_proximity_warning,
                ))

        return alerts

    def _check_group(self, group: AgentGroup) -> list[RiskAlert]:
        """Check group-level risk."""
        alerts = []

        active_agents = [a for a in group.agents if a.active]
        if not active_agents:
            return alerts

        # Check if too many agents are disabled
        disabled_ratio = 1 - len(active_agents) / max(len(group.agents), 1)
        if disabled_ratio > 0.5:
            alerts.append(RiskAlert(
                level=RiskLevel.HIGH,
                agent_id=None,
                group_name=group.name,
                category="group_health",
                message=(
                    f"Group {group.name}: {disabled_ratio:.0%} agents disabled. "
                    f"Group may be underperforming systematically."
                ),
                metric_value=disabled_ratio,
                threshold=0.5,
            ))

        return alerts

    def _check_correlation(self, groups: list[AgentGroup]) -> list[RiskAlert]:
        """Check if too many agents are positioned in the same direction."""
        alerts = []
        long_count = 0
        short_count = 0
        total_positioned = 0

        for group in groups:
            for agent in group.agents:
                if not agent.account or not agent.active:
                    continue
                for pos in agent.account.positions.values():
                    total_positioned += 1
                    if pos.side == Side.LONG:
                        long_count += 1
                    else:
                        short_count += 1

        if total_positioned > 5:
            max_direction = max(long_count, short_count)
            direction_ratio = max_direction / total_positioned
            dominant = "LONG" if long_count > short_count else "SHORT"

            if direction_ratio >= self.config.correlation_alert_threshold:
                alerts.append(RiskAlert(
                    level=RiskLevel.MEDIUM,
                    agent_id=None,
                    group_name="ALL",
                    category="correlation",
                    message=(
                        f"High correlation: {direction_ratio:.0%} of all positions are "
                        f"{dominant} ({max_direction}/{total_positioned}). "
                        f"Portfolio may be over-exposed to one direction."
                    ),
                    metric_value=direction_ratio,
                    threshold=self.config.correlation_alert_threshold,
                ))

        return alerts

    def evaluate_agent_performance(self, agent: TradingAgent) -> dict:
        """Evaluate an agent's performance for teacher feedback.

        Returns a structured evaluation with grade, strengths, and weaknesses.
        """
        account = agent.account
        if not account or account.total_trades == 0:
            return {
                "grade": "N/A",
                "message": "Not enough data to evaluate",
                "pnl_pct": 0,
                "win_rate": 0,
                "trades": 0,
            }

        pnl_pct = account.pnl_percent
        win_rate = account.win_rate
        drawdown = account.max_drawdown
        trades = account.total_trades

        # Grade calculation
        if pnl_pct >= self.config.excellent_pnl_pct and win_rate >= self.config.excellent_win_rate:
            grade = "A+"
        elif pnl_pct >= self.config.good_pnl_pct and win_rate >= self.config.good_win_rate:
            grade = "A" if pnl_pct >= self.config.excellent_pnl_pct else "B+"
        elif pnl_pct >= 0 and win_rate >= self.config.poor_win_rate:
            grade = "B" if pnl_pct >= self.config.good_pnl_pct else "C"
        elif pnl_pct > self.config.poor_pnl_pct:
            grade = "D"
        elif pnl_pct > self.config.terrible_pnl_pct:
            grade = "F"
        else:
            grade = "F-"

        # Identify strengths & weaknesses
        strengths = []
        weaknesses = []

        if win_rate >= 0.55:
            strengths.append(f"Good win rate ({win_rate:.0%})")
        elif win_rate < 0.40:
            weaknesses.append(f"Low win rate ({win_rate:.0%}) — entry timing needs work")

        if drawdown < 0.10:
            strengths.append(f"Excellent risk control (DD={drawdown:.1%})")
        elif drawdown > 0.25:
            weaknesses.append(f"Excessive drawdown ({drawdown:.1%}) — reduce position sizes")

        if pnl_pct > 5:
            strengths.append(f"Strong profits (+{pnl_pct:.1f}%)")
        elif pnl_pct < -10:
            weaknesses.append(f"Heavy losses ({pnl_pct:.1f}%) — strategy may need overhaul")

        avg_pnl_per_trade = account.total_pnl / trades if trades > 0 else 0
        if avg_pnl_per_trade > 0:
            strengths.append(f"Positive expectancy (${avg_pnl_per_trade:.2f}/trade)")
        else:
            weaknesses.append(f"Negative expectancy (${avg_pnl_per_trade:.2f}/trade)")

        return {
            "grade": grade,
            "pnl_pct": round(pnl_pct, 2),
            "win_rate": round(win_rate, 4),
            "max_drawdown": round(drawdown, 4),
            "trades": trades,
            "avg_pnl_per_trade": round(avg_pnl_per_trade, 2),
            "strengths": strengths,
            "weaknesses": weaknesses,
            "fitness": round(agent.fitness, 2),
        }

    def get_risk_summary(self) -> dict:
        """Get an overall risk summary for the simulation."""
        critical = sum(1 for a in self.alerts if a.level == RiskLevel.CRITICAL)
        high = sum(1 for a in self.alerts if a.level == RiskLevel.HIGH)
        medium = sum(1 for a in self.alerts if a.level == RiskLevel.MEDIUM)

        return {
            "total_alerts": len(self.alerts),
            "critical": critical,
            "high": high,
            "medium": medium,
            "disabled_agents": len(self.disabled_agents),
            "total_historical_alerts": len(self.alerts_history),
            "risk_level": (
                RiskLevel.CRITICAL if critical > 0
                else RiskLevel.HIGH if high > 2
                else RiskLevel.MEDIUM if medium > 0
                else RiskLevel.LOW
            ).value,
            "turbulence_index": round(self.turbulence_index, 4),
            "symbol_crowding": self.symbol_crowding,
        }

    # === Turbulence Index (Yang et al., 2020) ===

    def calculate_turbulence(
        self, current_prices: dict[str, float], prev_prices: dict[str, float],
    ) -> float:
        """Calculate turbulence index using Mahalanobis distance of returns.

        From: "Deep RL for Automated Stock Trading: An Ensemble Strategy"
        Turbulence measures how unusual current market returns are compared
        to the historical distribution. High turbulence = abnormal market.

        Returns:
            Turbulence score (0 = normal, >1 = elevated, >2 = extreme)
        """
        # Calculate current returns
        current_returns = {}
        for symbol in current_prices:
            if symbol in prev_prices and prev_prices[symbol] > 0:
                ret = (current_prices[symbol] - prev_prices[symbol]) / prev_prices[symbol]
                current_returns[symbol] = ret

        if len(current_returns) < 2:
            return 0.0

        # Store for history
        self._returns_history.append(current_returns)
        if len(self._returns_history) < 20:
            return 0.0  # Need enough history

        # Build returns matrix from history
        symbols = sorted(current_returns.keys())
        n_hist = min(len(self._returns_history), 100)
        recent = self._returns_history[-n_hist:]

        returns_matrix = []
        for hist in recent:
            row = [hist.get(s, 0.0) for s in symbols]
            returns_matrix.append(row)

        returns_matrix = np.array(returns_matrix)
        if returns_matrix.shape[0] < 5:
            return 0.0

        # Mean and covariance of historical returns
        mu = np.mean(returns_matrix, axis=0)
        cov = np.cov(returns_matrix, rowvar=False)

        # Current return vector
        y = np.array([current_returns.get(s, 0.0) for s in symbols])
        diff = y - mu

        # Mahalanobis distance
        try:
            cov_inv = np.linalg.pinv(cov)  # Pseudo-inverse for stability
            turbulence = float(diff @ cov_inv @ diff)
            # Normalize by number of assets
            turbulence = turbulence / len(symbols)
        except np.linalg.LinAlgError:
            turbulence = 0.0

        self.turbulence_index = max(0.0, turbulence)
        self.turbulence_history.append(self.turbulence_index)

        return self.turbulence_index

    def get_turbulence_regime(self) -> str:
        """Classify current market based on turbulence.

        Thresholds from empirical analysis:
        - Normal: turbulence < 1.0
        - Elevated: 1.0 <= turbulence < 2.5
        - High: 2.5 <= turbulence < 5.0
        - Extreme: turbulence >= 5.0
        """
        t = self.turbulence_index
        if t >= 5.0:
            return "extreme"
        elif t >= 2.5:
            return "high"
        elif t >= 1.0:
            return "elevated"
        return "normal"

    # === Enhanced Crowding Detection ===

    def check_symbol_crowding(self, groups: list[AgentGroup]) -> list[RiskAlert]:
        """Per-symbol crowding detection (ABIDES-inspired).

        With 70 agents, strategy crowding on specific symbols is a real risk.
        Detects when too many agents pile into the same symbol/direction.
        """
        alerts = []
        self.symbol_crowding = {}

        for group in groups:
            for agent in group.agents:
                if not agent.account or not agent.active:
                    continue
                for pos in agent.account.positions.values():
                    if pos.symbol not in self.symbol_crowding:
                        self.symbol_crowding[pos.symbol] = {"LONG": 0, "SHORT": 0}
                    self.symbol_crowding[pos.symbol][pos.side.value] += 1

        for symbol, counts in self.symbol_crowding.items():
            total = counts["LONG"] + counts["SHORT"]
            if total < 5:
                continue
            dominant_count = max(counts["LONG"], counts["SHORT"])
            dominant_side = "LONG" if counts["LONG"] > counts["SHORT"] else "SHORT"
            ratio = dominant_count / total

            if ratio >= 0.90:
                alerts.append(RiskAlert(
                    level=RiskLevel.HIGH,
                    agent_id=None,
                    group_name="ALL",
                    category="symbol_crowding",
                    message=(
                        f"CROWDING on {symbol}: {ratio:.0%} agents are {dominant_side} "
                        f"({dominant_count}/{total}). Force diversification recommended."
                    ),
                    metric_value=ratio,
                    threshold=0.90,
                    action_taken="DIVERSIFICATION_ADVISED",
                ))
            elif ratio >= 0.80:
                alerts.append(RiskAlert(
                    level=RiskLevel.MEDIUM,
                    agent_id=None,
                    group_name="ALL",
                    category="symbol_crowding",
                    message=(
                        f"Moderate crowding on {symbol}: {ratio:.0%} agents are "
                        f"{dominant_side} ({dominant_count}/{total})."
                    ),
                    metric_value=ratio,
                    threshold=0.80,
                ))

        return alerts
